### PR TITLE
Fix blink drag and drop from composer. Fix #712

### LINKED ISSUE #712: Composer: Check drag and drop blinked

### PR DESCRIPTION
**Pull request by erikaperugachi**

### CODE REVIEW

File: email_composer/src/components/DropfileField.js [hunk 1]
```diff
@@ -12,9 +12,9 @@ const DropfileField = props => (
       (props.isDragActive ? ' dragActive' : '') +
       (props.isToolbarHidden ? ' toolbarHidden' : '')
     }
-    onDragLeave={props.onDragLeave}
-    onDragOver={props.onDragOver}
-    onDrop={props.onDrop}
+    onDragLeave={e => props.onDragLeave(e)}
+    onDragOver={e => props.onDragOver(e)}
+    onDrop={e => props.onDrop(e)}
```
Comment (Hirobreak) [inline email_composer/src/components/DropfileField.js]: why not just `onDrop={props.onDrop}` ?

Comment (erikaperugachi) [reply email_composer/src/components/DropfileField.js]: that know that this is the end spread of this props

Comment (Hirobreak) [reply email_composer/src/components/DropfileField.js]: I can live with that
